// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.proyecto.inicial.domain;

import com.proyecto.inicial.domain.Area;
import com.proyecto.inicial.domain.AreaDataOnDemand;
import com.proyecto.inicial.domain.AreaIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AreaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AreaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AreaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AreaIntegrationTest: @Transactional;
    
    @Autowired
    AreaDataOnDemand AreaIntegrationTest.dod;
    
    @Test
    public void AreaIntegrationTest.testCountAreas() {
        Assert.assertNotNull("Data on demand for 'Area' failed to initialize correctly", dod.getRandomArea());
        long count = Area.countAreas();
        Assert.assertTrue("Counter for 'Area' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AreaIntegrationTest.testFindArea() {
        Area obj = dod.getRandomArea();
        Assert.assertNotNull("Data on demand for 'Area' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Area' failed to provide an identifier", id);
        obj = Area.findArea(id);
        Assert.assertNotNull("Find method for 'Area' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Area' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AreaIntegrationTest.testFindAllAreas() {
        Assert.assertNotNull("Data on demand for 'Area' failed to initialize correctly", dod.getRandomArea());
        long count = Area.countAreas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Area', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Area> result = Area.findAllAreas();
        Assert.assertNotNull("Find all method for 'Area' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Area' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AreaIntegrationTest.testFindAreaEntries() {
        Assert.assertNotNull("Data on demand for 'Area' failed to initialize correctly", dod.getRandomArea());
        long count = Area.countAreas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Area> result = Area.findAreaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Area' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Area' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AreaIntegrationTest.testFlush() {
        Area obj = dod.getRandomArea();
        Assert.assertNotNull("Data on demand for 'Area' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Area' failed to provide an identifier", id);
        obj = Area.findArea(id);
        Assert.assertNotNull("Find method for 'Area' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyArea(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Area' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AreaIntegrationTest.testMergeUpdate() {
        Area obj = dod.getRandomArea();
        Assert.assertNotNull("Data on demand for 'Area' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Area' failed to provide an identifier", id);
        obj = Area.findArea(id);
        boolean modified =  dod.modifyArea(obj);
        Integer currentVersion = obj.getVersion();
        Area merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Area' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AreaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Area' failed to initialize correctly", dod.getRandomArea());
        Area obj = dod.getNewTransientArea(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Area' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Area' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Area' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AreaIntegrationTest.testRemove() {
        Area obj = dod.getRandomArea();
        Assert.assertNotNull("Data on demand for 'Area' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Area' failed to provide an identifier", id);
        obj = Area.findArea(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Area' with identifier '" + id + "'", Area.findArea(id));
    }
    
}
