// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.proyecto.inicial.domain;

import com.proyecto.inicial.domain.GrupoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GrupoIntegrationTest_Roo_Configurable {
    
    declare @type: GrupoIntegrationTest: @Configurable;
    
}
