// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.proyecto.inicial.domain;

import com.proyecto.inicial.domain.Grupo;
import com.proyecto.inicial.domain.GrupoDataOnDemand;
import com.proyecto.inicial.domain.PermisosDataOnDemand;
import com.proyecto.inicial.domain.SucursalDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect GrupoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GrupoDataOnDemand: @Component;
    
    private Random GrupoDataOnDemand.rnd = new SecureRandom();
    
    private List<Grupo> GrupoDataOnDemand.data;
    
    @Autowired
    PermisosDataOnDemand GrupoDataOnDemand.permisosDataOnDemand;
    
    @Autowired
    SucursalDataOnDemand GrupoDataOnDemand.sucursalDataOnDemand;
    
    public Grupo GrupoDataOnDemand.getNewTransientGrupo(int index) {
        Grupo obj = new Grupo();
        setNombre(obj, index);
        return obj;
    }
    
    public void GrupoDataOnDemand.setNombre(Grupo obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public Grupo GrupoDataOnDemand.getSpecificGrupo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Grupo obj = data.get(index);
        Long id = obj.getId();
        return Grupo.findGrupo(id);
    }
    
    public Grupo GrupoDataOnDemand.getRandomGrupo() {
        init();
        Grupo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Grupo.findGrupo(id);
    }
    
    public boolean GrupoDataOnDemand.modifyGrupo(Grupo obj) {
        return false;
    }
    
    public void GrupoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Grupo.findGrupoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Grupo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Grupo>();
        for (int i = 0; i < 10; i++) {
            Grupo obj = getNewTransientGrupo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
