// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.proyecto.inicial.domain;

import com.proyecto.inicial.domain.Permisos;
import com.proyecto.inicial.domain.PermisosDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PermisosDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PermisosDataOnDemand: @Component;
    
    private Random PermisosDataOnDemand.rnd = new SecureRandom();
    
    private List<Permisos> PermisosDataOnDemand.data;
    
    public Permisos PermisosDataOnDemand.getNewTransientPermisos(int index) {
        Permisos obj = new Permisos();
        setAbm(obj, index);
        setAutorizar(obj, index);
        setCargar(obj, index);
        setDescargar(obj, index);
        setNombre(obj, index);
        setRechazar(obj, index);
        return obj;
    }
    
    public void PermisosDataOnDemand.setAbm(Permisos obj, int index) {
        Boolean abm = Boolean.TRUE;
        obj.setAbm(abm);
    }
    
    public void PermisosDataOnDemand.setAutorizar(Permisos obj, int index) {
        Boolean autorizar = Boolean.TRUE;
        obj.setAutorizar(autorizar);
    }
    
    public void PermisosDataOnDemand.setCargar(Permisos obj, int index) {
        Boolean cargar = Boolean.TRUE;
        obj.setCargar(cargar);
    }
    
    public void PermisosDataOnDemand.setDescargar(Permisos obj, int index) {
        Boolean descargar = Boolean.TRUE;
        obj.setDescargar(descargar);
    }
    
    public void PermisosDataOnDemand.setNombre(Permisos obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void PermisosDataOnDemand.setRechazar(Permisos obj, int index) {
        Boolean rechazar = Boolean.TRUE;
        obj.setRechazar(rechazar);
    }
    
    public Permisos PermisosDataOnDemand.getSpecificPermisos(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Permisos obj = data.get(index);
        Long id = obj.getId();
        return Permisos.findPermisos(id);
    }
    
    public Permisos PermisosDataOnDemand.getRandomPermisos() {
        init();
        Permisos obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Permisos.findPermisos(id);
    }
    
    public boolean PermisosDataOnDemand.modifyPermisos(Permisos obj) {
        return false;
    }
    
    public void PermisosDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Permisos.findPermisosEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Permisos' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Permisos>();
        for (int i = 0; i < 10; i++) {
            Permisos obj = getNewTransientPermisos(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
