// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.proyecto.inicial.domain;

import com.proyecto.inicial.domain.Sucursal;
import com.proyecto.inicial.domain.SucursalDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SucursalDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SucursalDataOnDemand: @Component;
    
    private Random SucursalDataOnDemand.rnd = new SecureRandom();
    
    private List<Sucursal> SucursalDataOnDemand.data;
    
    public Sucursal SucursalDataOnDemand.getNewTransientSucursal(int index) {
        Sucursal obj = new Sucursal();
        setDireccion(obj, index);
        setNombre(obj, index);
        setTelefono(obj, index);
        return obj;
    }
    
    public void SucursalDataOnDemand.setDireccion(Sucursal obj, int index) {
        String direccion = "direccion_" + index;
        obj.setDireccion(direccion);
    }
    
    public void SucursalDataOnDemand.setNombre(Sucursal obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void SucursalDataOnDemand.setTelefono(Sucursal obj, int index) {
        String telefono = "telefono_" + index;
        obj.setTelefono(telefono);
    }
    
    public Sucursal SucursalDataOnDemand.getSpecificSucursal(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Sucursal obj = data.get(index);
        Long id = obj.getId();
        return Sucursal.findSucursal(id);
    }
    
    public Sucursal SucursalDataOnDemand.getRandomSucursal() {
        init();
        Sucursal obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Sucursal.findSucursal(id);
    }
    
    public boolean SucursalDataOnDemand.modifySucursal(Sucursal obj) {
        return false;
    }
    
    public void SucursalDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Sucursal.findSucursalEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Sucursal' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Sucursal>();
        for (int i = 0; i < 10; i++) {
            Sucursal obj = getNewTransientSucursal(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
